---
- hosts: [ 'build' ]

  vars_files:
    - group_vars/securedrop.yml
    - host_vars/app.yml
    - development-specific.yml

  roles:
    - { role: build-securedrop-app-code-deb-pkg, tags: [ "app-deb" ] }
    - { role: build-generic-pkg, tags: ["securedrop-ossec-server"], package_name: "securedrop-ossec-server" }
    - { role: build-generic-pkg, tags: ["securedrop-ossec-agent"], package_name: "securedrop-ossec-agent" }
    - { role: build-generic-pkg, tags: ["securedrop-keyring"], package_name: "securedrop-keyring" }

  sudo: yes
