---
- name: install fpf apt signing gpg key
  apt_key: >
    state=present
    data="{{ lookup('file', 'fpf-signing-key.pub') }}"
    keyring=/etc/apt/trusted.gpg.d/securedrop-keyring.gpg

- name: setup fpf apt repo
  apt_repository: >
    repo='deb [arch=amd64] {{ apt_repo_url }} {{ ansible_lsb.codename }} main'
    state=present
    update_cache=yes

- name: ensure the fpf apt repo keyring package is installed
  apt:
    pkg: securedrop-keyring
    state: present
